import type { Metadata } from 'next';
import { Spectral, Inter, Inder } from 'next/font/google';
import { ThemeProviders } from '../components/provider/providers';
import '../styles/globals.css';

const spectral = Spectral({
  weight: '400',
  variable: '--font-spectral',
  subsets: ['latin'],
});

const inter = Inter({
  variable: '--font-inter',
  subsets: ['latin'],
});

const inder = Inder({
  weight: '400',
  variable: '--font-inder',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${spectral.variable} ${inter.variable} ${inder.variable} antialiased`}
      >
        <ThemeProviders>{children}</ThemeProviders>
      </body>
    </html>
  );
}
